node {
  name: "x"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 227
        }
        dim {
          size: 227
        }
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv1_pad/Pad"
  op: "Pad"
  input: "x"
  input: "sequential/mobilenet_1.00_227/conv1_pad/Pad/paddings"
}
node {
  name: "sequential/mobilenet_1.00_227/conv1/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv1_pad/Pad"
  input: "sequential/mobilenet_1.00_227/conv1/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv1_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv1/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv1_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv1_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv1_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv1_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv1_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv1_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_1/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv1_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_1/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_1_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_1/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_1_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_1_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_1_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_1_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_1_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_1_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_1/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_1_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_1/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_1_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_1/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_1_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_1_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_1_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_1_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_1_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_1_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pad_2/Pad"
  op: "Pad"
  input: "sequential/mobilenet_1.00_227/conv_pw_1_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pad_2/Pad/paddings"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_2/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pad_2/Pad"
  input: "sequential/mobilenet_1.00_227/conv_dw_2/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_2_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_2/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_2_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_2_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_2_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_2_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_2_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_2_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_2/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_2_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_2/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_2_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_2/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_2_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_2_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_2_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_2_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_2_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_2_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_3/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_2_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_3/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_3_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_3/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_3_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_3_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_3_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_3_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_3_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_3_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_3/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_3_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_3/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_3_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_3/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_3_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_3_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_3_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_3_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_3_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_3_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pad_4/Pad"
  op: "Pad"
  input: "sequential/mobilenet_1.00_227/conv_pw_3_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pad_4/Pad/paddings"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_4/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pad_4/Pad"
  input: "sequential/mobilenet_1.00_227/conv_dw_4/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_4_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_4/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_4_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_4_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_4_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_4_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_4_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_4_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_4/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_4_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_4/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_4_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_4/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_4_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_4_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_4_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_4_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_4_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_4_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_5/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_4_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_5/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_5_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_5/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_5_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_5_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_5_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_5_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_5_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_5_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_5/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_5_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_5/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_5_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_5/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_5_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_5_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_5_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_5_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_5_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_5_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pad_6/Pad"
  op: "Pad"
  input: "sequential/mobilenet_1.00_227/conv_pw_5_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pad_6/Pad/paddings"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_6/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pad_6/Pad"
  input: "sequential/mobilenet_1.00_227/conv_dw_6/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_6_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_6/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_6_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_6_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_6_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_6_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_6_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_6_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_6/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_6_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_6/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_6_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_6/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_6_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_6_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_6_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_6_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_6_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_6_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_7/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_6_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_7/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_7_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_7/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_7_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_7_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_7_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_7_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_7_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_7_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_7/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_7_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_7/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_7_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_7/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_7_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_7_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_7_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_7_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_7_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_7_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_8/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_7_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_8/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_8_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_8/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_8_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_8_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_8_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_8_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_8_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_8_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_8/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_8_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_8/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_8_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_8/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_8_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_8_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_8_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_8_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_8_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_8_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_9/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_8_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_9/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_9_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_9/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_9_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_9_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_9_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_9_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_9_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_9_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_9/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_9_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_9/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_9_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_9/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_9_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_9_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_9_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_9_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_9_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_9_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_10/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_9_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_10/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_10_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_10/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_10_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_10_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_10_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_10_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_10_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_10_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_10/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_10_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_10/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_10_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_10/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_10_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_10_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_10_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_10_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_10_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_10_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_11/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_10_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_11/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_11_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_11/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_11_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_11_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_11_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_11_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_11_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_11_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_11/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_11_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_11/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_11_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_11/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_11_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_11_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_11_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_11_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_11_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_11_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pad_12/Pad"
  op: "Pad"
  input: "sequential/mobilenet_1.00_227/conv_pw_11_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pad_12/Pad/paddings"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_12/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pad_12/Pad"
  input: "sequential/mobilenet_1.00_227/conv_dw_12/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_12_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_12/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_12_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_12_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_12_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_12_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_12_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_12_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_12/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_12_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_12/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_12_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_12/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_12_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_12_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_12_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_12_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_12_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_12_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_13/depthwise"
  op: "DepthwiseConv2dNative"
  input: "sequential/mobilenet_1.00_227/conv_pw_12_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_13/depthwise/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_13_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_dw_13/depthwise"
  input: "sequential/mobilenet_1.00_227/conv_dw_13_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_13_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_13_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_dw_13_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_dw_13_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_dw_13_bn/FusedBatchNormV3"
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_13/Conv2D"
  op: "Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_dw_13_relu/Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_13/Conv2D/ReadVariableOp/resource"
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "explicit_paddings"
    value {
      list {
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "SAME"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_13_bn/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_13/Conv2D"
  input: "sequential/mobilenet_1.00_227/conv_pw_13_bn/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_13_bn/ReadVariableOp_1/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_13_bn/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/mobilenet_1.00_227/conv_pw_13_bn/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/mobilenet_1.00_227/conv_pw_13_relu/Relu6"
  op: "Relu6"
  input: "sequential/mobilenet_1.00_227/conv_pw_13_bn/FusedBatchNormV3"
}
node {
  name: "sequential/batch_normalization/FusedBatchNormV3"
  op: "FusedBatchNormV3"
  input: "sequential/mobilenet_1.00_227/conv_pw_13_relu/Relu6"
  input: "sequential/batch_normalization/ReadVariableOp/resource"
  input: "sequential/batch_normalization/ReadVariableOp_1/resource"
  input: "sequential/batch_normalization/FusedBatchNormV3/ReadVariableOp/resource"
  input: "sequential/batch_normalization/FusedBatchNormV3/ReadVariableOp_1/resource"
  attr {
    key: "U"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "exponential_avg_factor"
    value {
      f: 1.0
    }
  }
}
node {
  name: "sequential/global_average_pooling2d/Mean"
  op: "Mean"
  input: "sequential/batch_normalization/FusedBatchNormV3"
  input: "sequential/global_average_pooling2d/Mean/reduction_indices"
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
node {
  name: "sequential/dense/MatMul"
  op: "MatMul"
  input: "sequential/global_average_pooling2d/Mean"
  input: "sequential/dense/MatMul/ReadVariableOp/resource"
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "sequential/dense/BiasAdd"
  op: "BiasAdd"
  input: "sequential/dense/MatMul"
  input: "sequential/dense/BiasAdd/ReadVariableOp/resource"
}
node {
  name: "sequential/dense/Relu"
  op: "Relu"
  input: "sequential/dense/BiasAdd"
}
node {
  name: "sequential/dense_1/MatMul"
  op: "MatMul"
  input: "sequential/dense/Relu"
  input: "sequential/dense_1/MatMul/ReadVariableOp/resource"
  attr {
    key: "transpose_a"
    value {
      b: false
    }
  }
  attr {
    key: "transpose_b"
    value {
      b: false
    }
  }
}
node {
  name: "sequential/dense_1/BiasAdd"
  op: "BiasAdd"
  input: "sequential/dense_1/MatMul"
  input: "sequential/dense_1/BiasAdd/ReadVariableOp/resource"
}
node {
  name: "sequential/dense_1/Softmax"
  op: "Softmax"
  input: "sequential/dense_1/BiasAdd"
}
node {
  name: "Identity"
  op: "Identity"
  input: "sequential/dense_1/Softmax"
}
